#!/usr/bin/env perl

$latex         = 'uplatex -halt-on-error -file-line-error -synctex=1 -shell-escape';
$bibtex        = 'upbibtex';
$biber         = 'biber -u -U --output_safechars';
$dvipdf        = 'dvipdfmx %O -o %D %S';
$max_repeat    = 5;
$pdf_mode      = 3;
$pdf_previewer = 'open -ga /Applications/Skim.app';
$pvc_view_file_via_temporary = 0;
